const ROLES = {
  ADMIN: 'ADMIN',
  DONOR: 'DONOR',
  USER: 'USER',
  HOSPITAL: 'HOSPITAL',
  BLOOD_BANK: 'BLOOD_BANK',
};

const REQUEST_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
};

const REQUEST_TARGET_TYPE = {
  DONOR: 'DONOR',
  BLOOD_BANK: 'BLOOD_BANK',
};

module.exports = {
  ROLES,
  REQUEST_STATUS,
  REQUEST_TARGET_TYPE,
};
